CREATE PROC CONTACTOS_ADD
@APELLIDO varchar(10),
@NOMBRE varchar(10),
@EDAD int, 
@DIRECCIÓN varchar(50),
@LOCALIDAD varchar(50),
@PROVINCIA varchar(50),
@E_MAIL varchar(50)
AS
INSERT INTO CONTACTOS (APELLIDO, NOMBRE, EDAD, DIRECCIÓN, LOCALIDAD, PROVINCIA, E_MAIL)
VALUES (@APELLIDO, @NOMBRE, @EDAD, @DIRECCIÓN, @LOCALIDAD, @PROVINCIA, @E_MAIL)